export const VIPBAR = [
    {
        image: "https://www.erepublik.com/images/icons/boosters/128px/speed.png",
        alt: "2x Damage Accelerator Icon",
        text: "2x Damage Accelerators",
        data: "gold",
        amount: 0.7,
        gold: true,
    },
    {
        image: "https://www.erepublik.com/images/icons/boosters/128px/damage.png",
        alt: "Ground Damage Icon",
        text: "+50% Ground Damage",
        data: "frm",
        amount: 13,
    },
    {
        image: "https://www.erepublik.com/images/icons/rewards/128px/storage.png",
        alt: "Storage Icon",
        text: "+1000 Storage",
        data: "frm",
        amount: 45,
    },
    {
        image: "https://www.erepublik.com/images/icons/industry/1/q10_128x128.png",
        alt: "Simple Energy Bar Icon",
        text: "Simple Energy Bar",
        data: "gold",
        amount: 1.4,
        gold: true,
    },
    {
        image: "https://www.erepublik.com/images/icons/boosters/128px/catchup.png",
        alt: "Ghost Booster Icon",
        text: "Ghost Booster",
        data: "wrm",
        amount: 51,
    },
    {
        image: "https://www.erepublik.com/images/icons/industry/1/q11_128x128.png",
        alt: "Double Energy Bar Icon",
        text: "Double Energy Bar",
        data: "gold",
        amount: 3,
        gold: true,
    },
    {
        image: "https://www.erepublik.com/images/icons/rewards/128px/factory_reset_token.png",
        alt: "Factory Reset Token Icon",
        text: "Factory Reset Token",
        data: "hrm",
        amount: 3,
    },
    {
        image: "https://www.erepublik.com/images/icons/boosters/128px/deploy_size.png",
        alt: "+100% Deploy Size Icon",
        text: "+100% Deploy Size",
        data: "frm",
        amount: 26,
    },
    {
        image: "https://www.erepublik.com/images/icons/boosters/128px/deploy_rank_ground.png",
        alt: "+10% Ground Rank Points Icon",
        text: "+10% Ground Rank Points",
        data: "wrm",
        amount: 129,
    },
    {
        image: "https://www.erepublik.com/images/icons/rewards/128px/storage.png",
        alt: "+9000 Storage Icon",
        text: "+9000 Storage",
        data: "wrm",
        amount: 238,
    },
    {
        image: "https://www.erepublik.com/images/icons/boosters/128px/air_damage.png",
        alt: "+20% Air Damage Icon",
        text: "+20% Air Damage",
        data: "arm",
        amount: 3,
    },
    {
        image: "https://www.erepublik.com/images/icons/boosters/128px/damage.png",
        alt: "+100% Ground Damage Icon",
        text: "+100% Ground Damage",
        data: "wrm",
        amount: 156,
    },
    {
        image: "https://www.erepublik.com/images/icons/boosters/128px/deploy_rank_air.png",
        alt: "+10% Air Rank Points Icon",
        text: "+10% Air Rank Points",
        data: "arm",
        amount: 6,
    },
    {
        image: "https://www.erepublik.com/images/icons/boosters/128px/speed.png",
        alt: "5x Damage Accelerators Icon",
        text: "5x Damage Accelerators",
        data: true,
        cc: 4481,
    },
    {
        image: "https://www.erepublik.com/images/icons/boosters/128px/deploy_rank_ground.png",
        alt: "+20% Ground Rank Points Icon",
        text: "+20% Ground Rank Points",
        data: "wrm",
        amount: 306,
    },
    {
        image: "https://www.erepublik.com/images/icons/boosters/128px/air_damage.png",
        alt: "+50% Air Damage Icon",
        text: "+50% Air Damage",
        data: "arm",
        amount: 7,
    },
];
